Repository AY2122S2-CS2103T-T12-2/tp, pull requests merged in 2022-04, with the labels that each got.

#189 Update create tag section in UG
  docs/UserGuide.md
  docs/images/assign-tag/assign-1-friends.png
  docs/images/assign-tag/assign-3-colleagues.png
  docs/images/assign-tag/before-assign-1-friends.png
  docs/images/assign-tag/before-assign-3-colleagues.png
  docs/images/assign-tag/view-1.png
  docs/images/assign-tag/view-assign-client.png
  docs/images/create-tag/create-tag-friends.png
  docs/images/del-tag/before-deltag-friends-colleagues-not-exist.png
  docs/images/del-tag/before-deltag-friends-colleagues.png
  docs/images/del-tag/before-deltag-friends.png
  docs/images/del-tag/deltag-colleagues-not-exist.png
  docs/images/del-tag/deltag-friends-colleagues-not-exist.png
  docs/images/del-tag/deltag-friends-colleagues.png
  docs/images/del-tag/deltag-friends.png
  docs/images/findtag/findtag-friends-inprogress-almostfinished.png
  docs/images/findtag/findtag-friends.png
  docs/images/unassign-tag/before-unassign-1-friends.png
  docs/images/unassign-tag/unassign-1-friends.png
  docs/images/unassign-tag/view-1.png
  docs/images/unassign-tag/view-unassign-client.png
Labels: type.Site

#190 Update help window and screenshot of help window
  docs/UserGuide.md
  docs/images/helpMessage.png
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: priority.High, type.Improvements

#192 Add borders to notes and deadline sections for detailed view
  src/main/java/seedu/address/ui/DetailedPersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DetailedPersonCard.fxml
Labels: type.Improvements

#197 Update PPP and DG
  docs/DeveloperGuide.md
  docs/diagrams/FindTagSequenceDiagram.puml
  docs/images/FindTagSequenceDiagram.png
  docs/team/glennljw.md
Labels: type.Site

#198 Update screenshots for tag related features with new GUI changes
  docs/images/Ui.png
  docs/images/assign-tag/assign-1-friends.png
  docs/images/assign-tag/assign-3-colleagues.png
  docs/images/assign-tag/before-assign-1-friends.png
  docs/images/assign-tag/before-assign-3-colleagues.png
  docs/images/assign-tag/view-1.png
  docs/images/assign-tag/view-assign-client.png
  docs/images/create-tag/create-tag-friends.png
  docs/images/del-tag/before-deltag-friends-colleagues-not-exist.png
  docs/images/del-tag/before-deltag-friends-colleagues.png
  docs/images/del-tag/before-deltag-friends.png
  docs/images/del-tag/deltag-colleagues-not-exist.png
  docs/images/del-tag/deltag-friends-colleagues-not-exist.png
  docs/images/del-tag/deltag-friends-colleagues.png
  docs/images/del-tag/deltag-friends.png
  docs/images/unassign-tag/before-unassign-1-friends.png
  docs/images/unassign-tag/unassign-1-friends.png
  docs/images/unassign-tag/view-1.png
  docs/images/unassign-tag/view-unassign-client.png
  docs/team/glennljw.md
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/d_interieur.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: type.Site

#200 UG fixes
  docs/UserGuide.md
  docs/images/after_unfavourite_command.png
  docs/images/favourite_command.png
  docs/images/findAlexDavidResult.png
  docs/images/high-importance-flag/add_importance_flag.png
  docs/images/high-importance-flag/add_note_for_reason.png
  docs/images/high-importance-flag/before_command.png
  docs/images/high-importance-flag/command_result.png
  docs/images/high-importance-flag/impts_command_result.png
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: documentation, type.Site

#202 Update PPP
  docs/AboutUs.md
  docs/team/xsaints19x.md
Labels: documentation, type.Site

#205 Update PPP remove linebreak
  docs/team/glennljw.md
Labels: type.Site

#206 Update images history ug and add tutorial
  docs/UserGuide.md
  docs/images/Sample1.png
  docs/images/Sample2.png
  docs/images/TutorialAdd.png
  docs/images/TutorialFav.png
  docs/images/TutorialImpt.png
  docs/images/TutorialView.png
Labels: type.Site

#210 Update DG
  docs/DeveloperGuide.md
Labels: type.Site

#215 Update Ezekiel's PPP
  docs/team/takufunkai.md
Labels: type.Site

#216 Fix bug where adding new images was not reflected
  src/main/java/seedu/address/logic/commands/AddImageCommand.java
Labels: bug
