Repository AY2122S2-CS2103T-T12-2/tp, pull requests merged in 2022-03, with the labels that each got.

#15 Update readme
  README.md
  docs/images/Ui.png
Labels: documentation

#24 Add deadline feature in user guide and change project name
  docs/UserGuide.md
Labels: type.Site

#26 Add find tag feature in User Guide
  docs/UserGuide.md
Labels: type.Site

#20 Update Developer Guide for v1.1
  docs/DeveloperGuide.md
Labels: type.Site

#28 Add Wei Jue's PPP and Note command to UG
  docs/UserGuide.md
  docs/team/takufunkai.md
  docs/team/weijuey.md
  docs/team/xsaints19x.md
Labels: documentation, type.Site

#35 Update release link for dinterieur.jar
  docs/UserGuide.md
Labels: type.Site

#38 Add find tag feature
  src/main/java/seedu/address/logic/commands/FindTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindTagCommandParser.java
  src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
Labels: type.Story

#37 Add favourites
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FavouriteCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FavouriteCommandParser.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/Favourite.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Story

#42 Enhance add command to take address as optional field
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Labels: type.Story, priority.Medium

#44 Add Deadline
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeadlineCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FavouriteCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeadlineCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Deadline.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: enhancement

#45 Add notes to contact and note command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeadlineCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FavouriteCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/NoteCommandParser.java
  src/main/java/seedu/address/model/person/Notes.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/NoteCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement, priority.High

#47 Add favourites test
  src/main/java/seedu/address/logic/commands/FavouriteCommand.java
  src/main/java/seedu/address/model/person/Favourite.java
  src/test/java/seedu/address/logic/commands/FavouriteCommandTest.java
  src/test/java/seedu/address/model/person/FavouriteTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: type.Story

#53 `JsonAdaptedPersonTest` hotfix
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: bug

#48 List favourites
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ListFavouritesCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/person/PersonIsFavouriteContactPredicate.java
  src/test/java/seedu/address/logic/commands/ListFavouritesCommandTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story

#55 Favourites UI
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
Labels: type.Improvements

#60 Allow multiple deadlines to be added with descriptions associated
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeadlineCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FavouriteCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/DeadlineCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Deadline.java
  src/main/java/seedu/address/model/person/DeadlineList.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedDeadline.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/DeadlineCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Improvements

#67 Fix `Persons#equals` and add negative tests
  src/main/java/seedu/address/model/person/Person.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: bug

#74 Add Deadline implementation in DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeadlineSequenceDiagram.puml
  docs/diagrams/DeadlineState1.puml
  docs/diagrams/DeadlineState2.puml
  docs/diagrams/DeadlineState3.puml
  docs/diagrams/DeadlineState4.puml
  docs/images/DeadlineSequenceDiagram.png
  docs/images/DeadlineState1.png
  docs/images/DeadlineState2.png
  docs/images/DeadlineState3.png
  docs/images/DeadlineState4.png
  src/main/java/seedu/address/logic/parser/DeadlineCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: documentation

#76 Add favourite feature into Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/favourite/FavouriteSequenceDiagram.puml
  docs/diagrams/favourite/FavouriteState0.puml
  docs/diagrams/favourite/FavouriteState1.puml
  docs/diagrams/favourite/FavouriteState2.puml
  docs/diagrams/favourite/FavouriteState3.puml
  docs/images/favourite/FavouriteSequenceDiagram.png
  docs/images/favourite/FavouriteState0.png
  docs/images/favourite/FavouriteState1.png
  docs/images/favourite/FavouriteState2.png
  docs/images/favourite/FavouriteState3.png
Labels: type.Site

#77 Update Developer Guide with Enhanced `Add` command and add high importance flag feature
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/HighImportanceSequenceDiagram.puml
  docs/diagrams/style.puml
  docs/images/AddCommandParserEnhancement.png
  docs/images/HighImportanceSequenceDiagram.png
Labels: documentation

#78 Fix UG formatting
  docs/UserGuide.md
Labels: documentation

#85 Images feature
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddImageCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeadlineCommand.java
  src/main/java/seedu/address/logic/commands/DeleteImageCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FavouriteCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/HighImportanceCommand.java
  src/main/java/seedu/address/logic/commands/ImagesCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddImageCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteImageCommandParser.java
  src/main/java/seedu/address/logic/parser/ImagesCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/image/ImageDetails.java
  src/main/java/seedu/address/model/image/ImageDetailsList.java
  src/main/java/seedu/address/model/image/exceptions/ImageDetailsNotFoundException.java
  src/main/java/seedu/address/model/image/util/ImageUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedImageDetails.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/ImageCard.java
  src/main/java/seedu/address/ui/ImageViewPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ImageCard.fxml
  src/main/resources/view/ImageViewPanel.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/data/testImages/test_image_1.png
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/model/image/ImageDetailsTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story

#90 Add create tag, assign tag, unassign tag features to UG
  docs/UserGuide.md
Labels: type.Site

#88 Update UG for adding high importance flag and listing contacts with high importance
  docs/UserGuide.md
Labels: documentation

#83 Add feature to assign and unassign tags to contacts
  src/main/java/seedu/address/logic/commands/AssignTagCommand.java
  src/main/java/seedu/address/logic/commands/CreateTagCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/UnassignTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AssignTagCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/UnassignTagCommandParser.java
  src/test/java/seedu/address/logic/commands/AssignTagCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/UnassignTagCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Story, priority.High

#94 Add delete tag feature
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/address/logic/commands/UnassignTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CreateTagCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteTagCommandParser.java
Labels: priority.High

#92 Update UG and create sort command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/AfterDeadlineCommand.jpg
  docs/images/BeforeDeadlineCommand.png
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/DeadlineCommand.java
  src/main/java/seedu/address/logic/commands/SortsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/comparator/AddressComparator.java
  src/main/java/seedu/address/model/comparator/DeadlineComparator.java
  src/main/java/seedu/address/model/comparator/DeadlineListComparator.java
  src/main/java/seedu/address/model/comparator/EmailComparator.java
  src/main/java/seedu/address/model/comparator/FavouriteComparator.java
  src/main/java/seedu/address/model/comparator/HighImportanceComparator.java
  src/main/java/seedu/address/model/comparator/NameComparator.java
  src/main/java/seedu/address/model/comparator/PhoneComparator.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Deadline.java
  src/main/java/seedu/address/model/person/DeadlineList.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Favourite.java
  src/main/java/seedu/address/model/person/HighImportance.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: enhancement, priority.Medium

#106 Update command summary table in UG
  docs/UserGuide.md
Labels: documentation

#95 Update UG with delete tag feature
  docs/UserGuide.md
Labels: type.Story

#110 Update UG with more details
  docs/UserGuide.md
  docs/images/high-importance-flag/add_importance_flag.png
  docs/images/high-importance-flag/add_note_for_reason.png
  docs/images/high-importance-flag/before_command.png
  docs/images/high-importance-flag/command_result.png
  docs/images/high-importance-flag/impts_command_result.png
  docs/index.md
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: documentation

#115 Update findtag feature in UG
  docs/UserGuide.md
Labels: type.Site, type.Improvements

#114 Change findtag to work as a filter
  src/main/java/seedu/address/logic/commands/DeadlineCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FavouriteCommand.java
  src/main/java/seedu/address/logic/commands/FindTagCommand.java
  src/main/java/seedu/address/logic/commands/HighImportanceCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/parser/FindTagCommandParser.java
  src/test/java/seedu/address/logic/commands/DeadlineCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FavouriteCommandTest.java
  src/test/java/seedu/address/logic/commands/FindTagCommandTest.java
  src/test/java/seedu/address/logic/parser/FindTagCommandParserTest.java
Labels: type.Improvements

#103 Add images feature to user guide
  docs/UserGuide.md
  docs/images/image_index.png
  docs/images/images_file_chooser.png
  src/main/java/seedu/address/ui/DetailedPersonCard.java
  src/main/resources/view/DetailedPersonCard.fxml
Labels: type.Site

#112 Implement command history feature
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/commandhistory/CommandHistory.java
  src/main/java/seedu/address/model/commandhistory/CommandHistoryEntry.java
  src/main/java/seedu/address/model/commandhistory/exceptions/HistoryDoesNotExistException.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/CommandBox.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Story
